apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-adminer-nba-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-adminer-nba-stats
  template:
    metadata:
      labels:
        app: pg-adminer-nba-stats
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: nba_stats
            - name: POSTGRES_USER
              value: nbastatsuser
            - name: POSTGRES_PASSWORD
              value: nbastatspassword
          volumeMounts:
            - name: postgres-data-nba-stats
              mountPath: /var/lib/postgresql/data
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
      volumes:
        - name: postgres-data-nba-stats
          emptyDir: {} 
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
spec:
  type: NodePort
  selector:
    app: pg-adminer-nba-stats
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001  
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-nodeport
spec:
  type: NodePort
  selector:
    app: pg-adminer-nba-stats
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
