apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-nba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-nba
  template:
    metadata:
      labels:
        app: postgres-nba
    spec:
      containers:
        - name: postgres-nba
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: nba_stats
            - name: POSTGRES_USER
              value: nbastatsuser
            - name: POSTGRES_PASSWORD
              value: nbastatspassword
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc